// Turns tools/doodles.svg into the doodle background pattern inside style.css.
//   node tools/make-doodles.mjs
// Rewrites the block between the DOODLE-PATTERN markers (tests/unit/doodles.test.js fails if it is out of date).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const VARIANTS = {
  light: { stroke: "#1B2A3A", opacity: "0.075" },   // the app's dark ink, drawn very faintly on the light paper
  dark:  { stroke: "#ECEAE3", opacity: "0.07" }     // the app's light ink, drawn very faintly on the dark background
};
export const START = "/* DOODLE-PATTERN:START";
export const END = "/* DOODLE-PATTERN:END */";

/** The SVG for one variant, as a CSS-safe data URI (no extra file to upload, nothing to cache or forget). */
export function dataUri(svgSource, variant) {
  const v = VARIANTS[variant];
  const svg = svgSource.replace("%STROKE%", v.stroke).replace("%OPACITY%", v.opacity)
    .replace(/<!--[\s\S]*?-->/g, "").replace(/\s+/g, " ").replace(/> </g, "><").trim();
  // Percent-encoded rather than raw: every browser accepts this form inside url("..."), including the spaces.
  return "data:image/svg+xml," + svg.replace(/%/g, "%25").replace(/</g, "%3C").replace(/>/g, "%3E").replace(/#/g, "%23").replace(/ /g, "%20");
}

export function buildDoodleCss(root) {
  const src = fs.readFileSync(path.join(root, "tools", "doodles.svg"), "utf8");
  return `${START} (generated by tools/make-doodles.mjs from tools/doodles.svg: edit that file, not this block) */
:root { --doodles: url("${dataUri(src, "light")}"); }
:root[data-theme="dark"] { --doodles: url("${dataUri(src, "dark")}"); }
/* The tile is a vector, so it stays sharp at any resolution. Its size is chosen in Settings (Small is the default) and
   grows only gently with the screen, so the pattern reads as a fine texture on a phone, an iPad and a desktop alike
   instead of ballooning into big sparse stickers on a large screen. */
html { --doodle-tile: clamp(150px, calc(130px + 4vw), 200px); }
html[data-bg-pattern-size="medium"] { --doodle-tile: clamp(220px, calc(190px + 8vw), 300px); }
html[data-bg-pattern-size="large"] { --doodle-tile: clamp(320px, calc(260px + 14vw), 520px); }
html[data-bg-pattern="doodles"] body { background-image: var(--doodles); background-size: var(--doodle-tile); background-repeat: repeat; }
.pattern-card__preview--doodles { background-image: var(--doodles); background-size: var(--doodle-tile); }
${END}`;
}

export function applyDoodleCss(css, block) {
  const a = css.indexOf(START), b = css.indexOf(END);
  if (a < 0 || b < 0) throw new Error("style.css has no DOODLE-PATTERN markers");
  return css.slice(0, a) + block + css.slice(b + END.length);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const file = path.join(root, "style.css");
  fs.writeFileSync(file, applyDoodleCss(fs.readFileSync(file, "utf8"), buildDoodleCss(root)));
  console.log("style.css: doodle pattern rewritten from tools/doodles.svg");
}
